BEGIN;

CREATE TABLE IF NOT EXISTS public.talent_customer_status_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_health_status VARCHAR(32) NOT NULL UNIQUE,
    state_instructions TEXT NOT NULL,
    follow_up_action TEXT NOT NULL,
    created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT talent_customer_status_action_status_check CHECK (
        customer_health_status IN ('高活跃', '活跃', '稳定', '观察', '风险', '流失预警', '流失')
    )
);

CREATE TABLE IF NOT EXISTS public.private_customer_status_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_health_status VARCHAR(32) NOT NULL UNIQUE,
    state_instructions TEXT NOT NULL,
    follow_up_action TEXT NOT NULL,
    created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT private_customer_status_action_status_check CHECK (
        customer_health_status IN ('高活跃', '活跃', '稳定', '观察', '风险', '流失预警', '流失')
    )
);

CREATE TABLE IF NOT EXISTS public.distribution_customer_status_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_health_status VARCHAR(32) NOT NULL UNIQUE,
    state_instructions TEXT NOT NULL,
    follow_up_action TEXT NOT NULL,
    created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT distribution_customer_status_action_status_check CHECK (
        customer_health_status IN ('高活跃', '活跃', '稳定', '观察', '风险', '流失预警', '流失')
    )
);

INSERT INTO public.talent_customer_status_action
    (customer_health_status, state_instructions, follow_up_action)
VALUES
    ('高活跃', '核心合作客户，销售与拿货表现突出', '重点维护，优先同步新品与重点活动'),
    ('活跃', '合作稳定，保持较高购买与拿货频率', '保持常规跟进，推动向高活跃转化'),
    ('稳定', '持续产生交易，整体表现较为平稳', '定期触达，关注销售与拿货变化'),
    ('观察', '近期活跃程度一般，需要继续观察', '了解需求，提供适配商品和活动信息'),
    ('风险', '销售或拿货表现出现明显下降', '主动联系，排查下降原因并制定改善计划'),
    ('流失预警', '较长时间未产生有效交易，存在流失可能', '安排专项召回，记录客户反馈和结果'),
    ('流失', '已达到业务定义的流失条件', '归档流失原因，保留低频唤醒计划')
ON CONFLICT (customer_health_status) DO NOTHING;

INSERT INTO public.private_customer_status_action
    (customer_health_status, state_instructions, follow_up_action)
SELECT customer_health_status, state_instructions, follow_up_action
FROM public.talent_customer_status_action
ON CONFLICT (customer_health_status) DO NOTHING;

INSERT INTO public.distribution_customer_status_action
    (customer_health_status, state_instructions, follow_up_action)
SELECT customer_health_status, state_instructions, follow_up_action
FROM public.talent_customer_status_action
ON CONFLICT (customer_health_status) DO NOTHING;

COMMIT;
